### ISSUE TITLE
Crashes every time I click on Cache

### ISSUE THREAD

**Issue by BorisTB** [apollographql/apollo-client-devtools#107]
Everytime I click on cache it just crashes. But only if there's anything stored in cache. I can open Cache tab when cache is empty, but it crashes as soon as something is added to it.

**useragent**
rawUa: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3350.0 Safari/537.36
string:
family: Chrome
major: 66
minor: 0
patch: 3350
device: Other 0.0.0

**OS**
string: Mac OS X 10.13.3
family: Mac OS X
major: 10
minor: 13
patch: 3

**Comment by tnrich** [comment]
I can second that this is happening for me as well:
![image](https://user-images.githubusercontent.com/2730609/36456564-5dbfc3c4-165a-11e8-896a-018a31d3138d.png)

Also, does anyone know what that 

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' <URL> <URL>".
```

error message is about?

**Comment by Herlevsen** [comment]
Same thing happens for me

Mac OS 10.13.3
Chrome 65.0.3325.162

**Comment by przemkow** [comment]
Same problem,

Mac OS 10.13.4
Chrome 65.0.3325.181

I wanted to check if firefox plugin crash as well but I couldn't find apollo client devtools on addons.mozilla.org anymore.

**Comment by AlexLi88** [comment]
same here 
Chrome Version 66.0.3359.181 (Official Build) (64-bit)  
Max OS 10.13.4 (17E202)

**Comment by BorisTB** [comment]
Does anyone from the apollo-client-devtools team noticed this issue? Can you please give some statement? If MacOS is not (and will not be) supported, please let us know.

**Comment by lucianD** [comment]
I have the same issue using Mac OS

**Comment by rijulg** [comment]
I found a similar, but not the same problem. 
While using Vue.js with Apollo the Cache tab crashed without any errors with basic configuration. 

However adding 
`tokenName: 'apollo-token',`
in the apollo client solved the issue for me

```js
import VueApollo from 'vue-apollo';
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';

// Name of the localStorage item
const LOCAL_STORAGE_TOKEN = 'apollo-token';

const httpLink = new HttpLink({
  // You should use an absolute URL here
  uri: 'http://localhost:3020/graphql',
});

// Create the apollo client
const apolloClient = new ApolloClient({
  link: httpLink,
  tokenName: LOCAL_STORAGE_TOKEN,
  cache: new InMemoryCache(),
  connectToDevTools: true,
});

export default new VueApollo({
  defaultClient: apolloClient,
});
```

**Comment by MattReimer** [comment]
I'm seeing the same thing. I tried @rijulg 's and the error went away but Queries, Mutations and Cache are empty windows. 

One interesting thing is that the GraphiQL window works perfectly and I'm able to run queries and auto-complete just fine.

**Comment by cs-miller** [comment]
Still an issue for me, all my queries include ids.

**Comment by nomadoda** [comment]
Same issue, macOS, triggered during implementation of apollo-link-error

**Comment by faurehu** [comment]
I've got this, although it is fixed when a `writeQuery` is done successfully in my webapp and reloading the panel page.

Before it, the variable `window.__APOLLO_CLIENT__.cache.data.data` is an empty object `{}`.

I suspect the extension is expecting something else and cannot render without a populated object.

**Comment by ianshea** [comment]
I had to remove and reinstall the extension to get it working again.

FWIW , I tried `client.clearStore()` and `client.resetStore()` to remove cached data and the issue persisted.

**Comment by TejasQ** [comment]
@peggyrayzis and team any responses to this?

**Comment by justinanastos** [comment]
Hey y'all. Sorry for the very long response time. Can someone post a minimal reproduction?

I tried using Apollo's full stack tutorial both using the latest prod versions of `react-apollo` and `apollo-client` (https://github.com/justinanastos/fullstack-tutorial/tree/justin/apollo-pre-2.5) and pre-release alphas (https://github.com/apollographql/fullstack-tutorial).

I can see the cache in both cases.

![image](https://user-images.githubusercontent.com/5224118/52582792-088d5780-2dfc-11e9-9d33-ea27a857962b.png)

Obviously this is not some one-off error if so many people have commented on it. Can someone please post a minimal reproduction?

**Comment by jfrej** [comment]
In my case this is linked to clearing the cache. Everything works until the cache is cleared.
I've just removed the extension, restarted Chrome and re-added the extension. The problem persists.

So here's a reproduction:
1. Open https://kry9my57o.codesandbox.io/ (the source: https://codesandbox.io/s/kry9my57o )
2. Open Apollo Dev Tools
3. Go to the Cache tab and check that everything is working (there should be a `ROOT_QUERY` and a single cached object)
4. Click on the "Clear" button in the page. This calls `client.clearStore()`. The cache tab in Dev Tools should now be empty. I don't think this ever worked, though. You can switch between different tabs and it will still work and show the populated cache.
5. Right-click within the extension window and choose "Reload Frame" (or close and re-open Apollo Dev Tools)
7. Click on the Cache tab

The extension will now crash showing a blank screen as per the screenshot in https://github.com/apollographql/apollo-client-devtools/issues/107#issuecomment-367169597

I think I remember this working before - it would normally reload showing the empty cache.

There are errors in the browser console for the Apollo extension frame:
`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)`

![image](https://user-images.githubusercontent.com/11192156/52601549-0e645680-2e57-11e9-8cb1-ded19cb6eb69.png)

**Comment by justinanastos** [comment]
Thank you @jfrej ! I ran through the reproduction and saw exactly what you explained. I'm actively working on Apollo Client Devtools for the time being so hopefully I have something to report soon :)

Thanks again!

**Comment by justinanastos** [comment]
Resolved in [v2.1.7](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.1.7)
