### ISSUE TITLE
New version does not fill in query variables.

### ISSUE THREAD

**Issue by andrewbihl** [apollographql/apollo-client-devtools#495]
In the old version, one could open the Apollo tab, select a query, and re-run it with the variable input that were used on its last execution. This is no longer present in the new version.

**Intended outcome:**

I can re-run queries in the Apollo tab.

**Actual outcome:**

I cannot.

**How to reproduce the issue:**

**Desktop (please complete the following information):**
 - Browser version [e.g. 22]
 - Extension version [e.g. 3.0]

Chrome 89.0.4389.90

**Comment by seandearnaley** [comment]
+1

**Comment by hwillson** [comment]
@andrewbihl this was fixed in https://github.com/apollographql/apollo-client-devtools/pull/491 and will be included in the next release. Thanks!

**Comment by kojuka** [comment]
@hwillson I'm still seeing this even after the 3.0.3 release.  No variables getting filled for my queries.  Anyone else?

**Comment by seandearnaley** [comment]
yeah no variables for me either

**Comment by kojuka** [comment]
FYI - I was actually able to [download v2.3.5](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.3.5), build it locally and install it.  Problem solved.  I'll try version 3 again after a few of these issues have been resolved.  

Love this tool and have become pretty dependent on it as part of our dev workflow.

**Comment by seandearnaley** [comment]
thanks @kojuka I'll have to do that
